StylesPath = .github/styles
Packages = https://github.com/vale-cli/MDX/releases/download/v0.3.0/MDX.zip, https://github.com/vale-cli/Google/releases/download/v0.7.1/Google.zip
MinAlertLevel = warning

[*.mdx]
BasedOnStyles = Steel

# Start with objective, low-noise Google developer documentation rules.
Google.Gender = warning
Google.GenderBias = warning
Google.HeadingPunctuation = warning
Google.Latin = warning
Google.LyHyphens = warning
Google.OptionalPlurals = warning
Google.Quotes = warning
Google.Spacing = warning
